"""empty message

Revision ID: 0dc11cf2f32b
Revises: aebbae89cda0
Create Date: 2022-05-25 20:06:00.960062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc11cf2f32b'
down_revision = 'aebbae89cda0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('away_settlement', sa.Boolean(), nullable=True))
    op.add_column('flat', sa.Column('numbers_of_room', sa.Integer(), nullable=True))
    op.add_column('flat', sa.Column('type_of_room', sa.String(length=64), nullable=True))
    op.add_column('flat', sa.Column('total_space', sa.Float(precision=5), nullable=True))
    op.add_column('flat', sa.Column('space_of_kitchen', sa.Float(precision=5), nullable=True))
    op.add_column('flat', sa.Column('space_of_living', sa.Float(precision=5), nullable=True))
    op.add_column('flat', sa.Column('furniture', sa.String(length=150), nullable=True))
    op.add_column('flat', sa.Column('technics', sa.String(length=150), nullable=True))
    op.add_column('flat', sa.Column('balcony_or_loggia', sa.String(length=150), nullable=True))
    op.add_column('flat', sa.Column('ceiling_height', sa.Float(precision=5), nullable=True))
    op.add_column('flat', sa.Column('bathroom', sa.String(length=150), nullable=True))
    op.add_column('flat', sa.Column('widow', sa.String(length=150), nullable=True))
    op.add_column('flat', sa.Column('repair', sa.String(length=150), nullable=True))
    op.add_column('flat', sa.Column('floor', sa.Integer(), nullable=False))
    op.add_column('flat', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_flat_away_settlement'), 'flat', ['away_settlement'], unique=False)
    op.create_index(op.f('ix_flat_ceiling_height'), 'flat', ['ceiling_height'], unique=False)
    op.create_index(op.f('ix_flat_floor'), 'flat', ['floor'], unique=False)
    op.create_index(op.f('ix_flat_numbers_of_room'), 'flat', ['numbers_of_room'], unique=False)
    op.create_index(op.f('ix_flat_space_of_kitchen'), 'flat', ['space_of_kitchen'], unique=False)
    op.create_index(op.f('ix_flat_space_of_living'), 'flat', ['space_of_living'], unique=False)
    op.create_index(op.f('ix_flat_total_space'), 'flat', ['total_space'], unique=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_flat_total_space'), table_name='flat')
    op.drop_index(op.f('ix_flat_space_of_living'), table_name='flat')
    op.drop_index(op.f('ix_flat_space_of_kitchen'), table_name='flat')
    op.drop_index(op.f('ix_flat_numbers_of_room'), table_name='flat')
    op.drop_index(op.f('ix_flat_floor'), table_name='flat')
    op.drop_index(op.f('ix_flat_ceiling_height'), table_name='flat')
    op.drop_index(op.f('ix_flat_away_settlement'), table_name='flat')
    op.drop_column('flat', 'description')
    op.drop_column('flat', 'floor')
    op.drop_column('flat', 'repair')
    op.drop_column('flat', 'widow')
    op.drop_column('flat', 'bathroom')
    op.drop_column('flat', 'ceiling_height')
    op.drop_column('flat', 'balcony_or_loggia')
    op.drop_column('flat', 'technics')
    op.drop_column('flat', 'furniture')
    op.drop_column('flat', 'space_of_living')
    op.drop_column('flat', 'space_of_kitchen')
    op.drop_column('flat', 'total_space')
    op.drop_column('flat', 'type_of_room')
    op.drop_column('flat', 'numbers_of_room')
    op.drop_column('flat', 'away_settlement')
    # ### end Alembic commands ###
