"""empty message

Revision ID: 340cef248eee
Revises: 
Create Date: 2022-06-03 14:22:14.645552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340cef248eee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('away_settlement', sa.Boolean(), nullable=True),
    sa.Column('numbers_of_room', sa.Integer(), nullable=True),
    sa.Column('type_of_room', sa.String(length=64), nullable=True),
    sa.Column('total_space', sa.Float(precision=5), nullable=True),
    sa.Column('space_of_kitchen', sa.Float(precision=5), nullable=True),
    sa.Column('space_of_living', sa.Float(precision=5), nullable=True),
    sa.Column('furniture', sa.String(length=150), nullable=True),
    sa.Column('technics', sa.String(length=150), nullable=True),
    sa.Column('balcony_or_loggia', sa.String(length=150), nullable=True),
    sa.Column('ceiling_height', sa.Float(precision=5), nullable=True),
    sa.Column('bathroom', sa.String(length=150), nullable=True),
    sa.Column('widow', sa.String(length=150), nullable=True),
    sa.Column('repair', sa.String(length=150), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flat_address'), 'flat', ['address'], unique=False)
    op.create_index(op.f('ix_flat_away_settlement'), 'flat', ['away_settlement'], unique=False)
    op.create_index(op.f('ix_flat_ceiling_height'), 'flat', ['ceiling_height'], unique=False)
    op.create_index(op.f('ix_flat_district'), 'flat', ['district'], unique=False)
    op.create_index(op.f('ix_flat_floor'), 'flat', ['floor'], unique=False)
    op.create_index(op.f('ix_flat_numbers_of_room'), 'flat', ['numbers_of_room'], unique=False)
    op.create_index(op.f('ix_flat_price'), 'flat', ['price'], unique=False)
    op.create_index(op.f('ix_flat_space_of_kitchen'), 'flat', ['space_of_kitchen'], unique=False)
    op.create_index(op.f('ix_flat_space_of_living'), 'flat', ['space_of_living'], unique=False)
    op.create_index(op.f('ix_flat_timestamp'), 'flat', ['timestamp'], unique=False)
    op.create_index(op.f('ix_flat_total_space'), 'flat', ['total_space'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('path', sa.Unicode(length=128), nullable=True),
    sa.Column('flat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flat_id'], ['flat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('image')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_index(op.f('ix_flat_total_space'), table_name='flat')
    op.drop_index(op.f('ix_flat_timestamp'), table_name='flat')
    op.drop_index(op.f('ix_flat_space_of_living'), table_name='flat')
    op.drop_index(op.f('ix_flat_space_of_kitchen'), table_name='flat')
    op.drop_index(op.f('ix_flat_price'), table_name='flat')
    op.drop_index(op.f('ix_flat_numbers_of_room'), table_name='flat')
    op.drop_index(op.f('ix_flat_floor'), table_name='flat')
    op.drop_index(op.f('ix_flat_district'), table_name='flat')
    op.drop_index(op.f('ix_flat_ceiling_height'), table_name='flat')
    op.drop_index(op.f('ix_flat_away_settlement'), table_name='flat')
    op.drop_index(op.f('ix_flat_address'), table_name='flat')
    op.drop_table('flat')
    # ### end Alembic commands ###
