"""empty message

Revision ID: 898c6213761f
Revises: 8e0d436c9e07
Create Date: 2022-06-06 18:59:45.123331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898c6213761f'
down_revision = '8e0d436c9e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('street', sa.String(length=64), nullable=True))
    op.add_column('flat', sa.Column('house', sa.Integer(), nullable=True))
    op.drop_index('ix_flat_address', table_name='flat')
    op.create_index(op.f('ix_flat_house'), 'flat', ['house'], unique=False)
    op.create_index(op.f('ix_flat_street'), 'flat', ['street'], unique=False)
    op.drop_column('flat', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('address', sa.VARCHAR(length=64), nullable=False))
    op.drop_index(op.f('ix_flat_street'), table_name='flat')
    op.drop_index(op.f('ix_flat_house'), table_name='flat')
    op.create_index('ix_flat_address', 'flat', ['address'], unique=False)
    op.drop_column('flat', 'house')
    op.drop_column('flat', 'street')
    # ### end Alembic commands ###
